spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/penny_pal
    username: root
    password: 1234
#    url: ${MYSQL_DATASOURCE_URL}
#    username: ${MYSQL_DATASOURCE_USERNAME}
#    password: ${MYSQL_DATASOURCE_PASSWORD}



#logging:
#  level:
#    org:
#      springframework:
#        web.client.RestTemplate: DEBUG
#        http: DEBUG
logging:
  level:
    org:
      springframework:
        security: DEBUG
---
spring:
  profiles:
    active: prods
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: local

