spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate.ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql=true:
        use_sql_comments=true:
